### ISSUE TITLE
symlinks doesnt work with react native.

### ISSUE THREAD

**Issue by jknair0** [erickjth/react-native-web-monorepo-lerna#2]
How were you able to solve this issue? Lerna creates symlinks that cannot be used by react native project.

**Comment by erick-di** [comment]
Hey @kjknair thanks for opening this. I will check it out, the project dependencies are very out-to-date, probably something is broken.

**Comment by erickjth** [comment]
Hey @kjknair thanks for opening this. I will check it out, the project dependencies are very out-to-date, probably something is broken.

**Comment by youngjuning** [comment]
any update? https://dushyant37.medium.com/how-to-use-lerna-with-react-native-1eaa79b5d8ec

**Comment by youngjuning** [comment]
![image](https://user-images.githubusercontent.com/13204332/124643324-8c5fa700-dec3-11eb-8bb1-043fc91277a2.png)

**Comment by erickjth** [comment]
Hey @youngjuning, Sadly, I am really running out of time to maintain this reposiory, but PRs are always open if you want to push some updates related to this issue, It would be helpful.
